# Generated by Django 3.1.3 on 2020-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0002_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
